GET http://localhost:3001/api/posts
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWWFyaWsiLCJwYXNzd29yZCI6IjEyMyIsImlhdCI6MTYxNDg0NDM2MiwiZXhwIjoxNjE0ODQ0Mzg3fQ.TWtdVPynIthzo1kJunQFwQLUEdtr9bxCq73rqnDVG8g

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "Yarik",
    "password": "123"
}

###

POST http://localhost:3001/api/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWWFyaWsiLCJwYXNzd29yZCI6IjEyMyIsImlhdCI6MTYxNDg0NDE3Nn0.KZGskwL_NyI1kN9Y_WTcsT2-bJp1fU5Z8VoTslM5meM"
}

###

DELETE http://localhost:3001/api/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWWFyaWsiLCJwYXNzd29yZCI6IjEyMyIsImlhdCI6MTYxNDg0NDE3Nn0.KZGskwL_NyI1kN9Y_WTcsT2-bJp1fU5Z8VoTslM5meM"
}