GET http://localhost:3001/api/posts
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWWFyaWsiLCJwYXNzd29yZCI6IjEyMyIsImlhdCI6MTYxNDg0NDM2MiwiZXhwIjoxNjE0ODQ0Mzg3fQ.TWtdVPynIthzo1kJunQFwQLUEdtr9bxCq73rqnDVG8g

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "Yarik",
    "password": "123"
}

###

POST http://localhost:3001/api/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWWFyaWsiLCJwYXNzd29yZCI6IjEyMyIsImlhdCI6MTYxNDg0NDE3Nn0.KZGskwL_NyI1kN9Y_WTcsT2-bJp1fU5Z8VoTslM5meM"
}

###

DELETE http://localhost:3001/api/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWWFyaWsiLCJwYXNzd29yZCI6IjEyMyIsImlhdCI6MTYxNDg0NDE3Nn0.KZGskwL_NyI1kN9Y_WTcsT2-bJp1fU5Z8VoTslM5meM"
}


###

GET http://localhost:3001/drive/list 
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWWFyaWsiLCJwYXNzd29yZCI6IjEyMyIsImlhdCI6MTYxNzgyMDE1NSwiZXhwIjoxNjE3ODIwMjE1fQ.XduMxEyMDWwaCGrstzFbGl5fWlSDHMlgGEzmPK6w6hE


###

POST http://localhost:3001/drive/getFile
Content-Type: application/json

# Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWWFyaWsiLCJwYXNzd29yZCI6IjEyMyIsImlhdCI6MTYxNjg2MTIzNSwiZXhwIjoxNjE2ODYxMjk1fQ.DXKnbFSIeuTbRMo0c9-vGHrHyFiadsswKrcaIUZvPc4
{
    "fileId": "1-1cBqIVaz8KCU9JItFqe-CGgKK-vcdE9",
    "Authorization":  "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWWFyaWsiLCJwYXNzd29yZCI6IjEyMyIsImlhdCI6MTYxNzQ1MjczOCwiZXhwIjoxNjE3NDUyNzk4fQ.r87Uht7rTS48xc-u9jOzZhVPIjZXwvMkCxVrj8-f-2Q"
}


###

POST https://www.googleapis.com/upload/drive/v3/files?uploadType=media
Content-Type: application/json

{
    "body": "HEHEHHEHEHEHEHHEHE)))"
}


###

DELETE http://localhost:3001/drive/deleteAFile
Content-Type: application/json

{
    "fileId": "1_X1psYHHyFBA4VmzWLJ1ZgEiFKYe3R18"
}

###

POST http://localhost:3001/drive/upload
Content-Type: application/json

{
    "filename": "new-test-google.txt",
    "fileId": "1FDIbr2uu-zU2PhfhQe34PMTDYRts3dzn"
}